[theme]
primaryColor="#e30913"
backgroundColor="#141414"
secondaryBackgroundColor="#595959"
textColor="#f5f5f1"
font="sans serif"


[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"


[global]
showWarningOnDirectExecution = false
